{{- if and .Values.persistence.content.enabled (not .Values.persistence.content.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx.fullname" . }}-content
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  {{- with .Values.persistence.content.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.content.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.content.size | quote }}
  {{- if .Values.persistence.content.storageClass }}
  {{- if (eq "-" .Values.persistence.content.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.content.storageClass }}"
  {{- end }}
  {{- end }}
---
{{- end -}}
{{- if and .Values.persistence.logs.enabled (not .Values.persistence.logs.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx.fullname" . }}-logs
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  {{- with .Values.persistence.logs.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size | quote }}
  {{- if .Values.persistence.logs.storageClass }}
  {{- if (eq "-" .Values.persistence.logs.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.logs.storageClass }}"
  {{- end }}
  {{- end }}
{{- end -}}
